### ISSUE TITLE
Scan to include Port

### ISSUE THREAD

**Issue by Lewiscowles1986** [vincentkelleher/OBDLib#1]
It would be nice if the scan utility was able to assess the port, or auto-assign, or just provide more information on finding what to send in via the port argument. I Have no clue what a valid option for port argument would be, but as it is a number, I'd assume a simple loop could find the port on a device (I'll do some testing and hopefully not kill the car).

**Comment by Lewiscowles1986** [comment]
https://pybluez.googlecode.com/svn/www/docs-0.7/public/bluetooth-module.html#get_available_port

Suggests there was a utility method in pybluez, but now it is acceptable to bind to port zero (I'm unsure if I understand what is meant by port in this context)

**Comment by vincentkelleher** [comment]
First of all, it's a long time since I started working on this project.
Then, after reading PyBluez's documentation, if you specify port 0 for the bluetooth communication, PyBluez selects it automatically.

Does this answer your question ?

**Comment by Lewiscowles1986** [comment]
Hi.

Yes I realize it might be an abandoned project, but don't ask, don't know :wink: 

The pyBluez documentation seems to generate an error when using zero as port number in this project, 1 seems to progress further, but then error out.

I'll keep hammering away...

**Comment by vincentkelleher** [comment]
What OBD device are you using ?

**Comment by Lewiscowles1986** [comment]
Bluetooth ELM-327 Mini from Amazon. It does not have a serial number and reports as "OBDII" as it's identifier over bluetooth.

**Comment by Lewiscowles1986** [comment]
Looks like this has nothing to do with your app; I think the hardware must be crappy as it's just failed with a few android readers as well... I've written to the manufacturer, but I'm closing the issue. thanks for the assist :+1:
